name: timeroute
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_dotenv: ^5.1.0
  url_strategy: ^0.2.0
  dio: ^5.4.3+1
  get: ^4.6.6

  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.6+2
  collection: ^1.18.0

  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Regular.ttf

  assets:
    - .env